from industry.lib.industry import symmetrize

enormous_set = symmetrize(
    [
        (
            "    xxxxxxxx    ",
            "  xxxxxxxxxxxx  ",
            " xxxxxxxxxxxxxx ",
            " xxxxxxxxxxxxxx ",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            " xxxxxxxxxxxxxx ",
            " xxxxxxxxxxxxxx ",
            "  xxxxxxxxxxxx  ",
            "    xxxxxxxx    ",
        ),
        (
            "    xxxxxxxx    ",
            "  xxxxxxxxxxxx  ",
            "  xxxxxxxxxxxxx ",
            " xxxxxxxxxxxxxx ",
            " xxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxx ",
            " xxxxxxxxxxxxxx ",
            " xxxxxxxxxxxxx  ",
            "  xxxxxxxxxxxx  ",
            "    xxxxxxxx    ",
        ),
        (
            "    xxxxxxx     ",
            "  xxxxxxxxxxx   ",
            "  xxxxxxxxxxxxx ",
            " xxxxxxxxxxxxxx ",
            " xxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxxx",
            "xxxxxxxxxxxxxxx ",
            " xxxxxxxxxxxxxx ",
            " xxxxxxxxxxxxx  ",
            "   xxxxxxxxxxx  ",
            "     xxxxxxx    ",
        ),
    ]
)
