from .normal import normal_demo
from .big import big_demo, big_half_demo
from .real_yard import real_yard_demo
from .full_auto import full_auto_demo
from .full_np_auto import full_np_auto_demo
from .semi_auto import semi_auto_demo
from .semi_np_auto import semi_np_auto_demo
from .side_auto import side_auto_demo
from .side_np_auto import side_np_auto_demo
from .side_third_auto import side_third_auto_demo
from .side_third_np_auto import side_third_np_auto_demo
from .special_g import special_demo_g
from .special_p import special_demo_p
from .special_cn import special_demo_cn
from .special_sa import special_demo_sa
from .special_cp import special_demo_cp
from .special_aq import special_demo_aq
from .west_plaza import west_plaza
from .west_plaza_oneliner import west_plaza_oneliner
from .west_plaza_oversized import west_plaza_oversized
from .west_plaza_one_tile import west_plaza_one_tile
