title: Ahyangyi's NewGRFs
description: >-
  Documentation for Ahyangyi's OpenTTD NewGRFs
baseurl: "/openttd-newgrfs"
url: "https://ahyangyi.github.io/"
github_username:  ahyangyi
theme: just-the-docs
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-mermaid
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js'
languages: ["en-GB", "zh-CN"]
exclude_from_localizations: ["js", "imgs", "css"]
markdown: kramdown
color_scheme: definibus
