title: Ahyangyi's NewGRFs
description: >-
  Documentation for Ahyangyi's OpenTTD NewGRFs
baseurl: "/openttd-newgrfs"
url: "https://ahyangyi.github.io/"
github_username:  ahyangyi
theme: just-the-docs
languages: ["en-GB", "zh-CN"]
markdown: kramdown
color_scheme: definibus
