name: Build Station

on:
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          lfs: true
      - name: Install golang deps
        run: ./install-go-dependencies.sh
      - name: Install system python deps
        run: sudo apt update && sudo apt install python3-ply python3-pil libjpeg-dev zlib1g-dev
      - name: Get setuptools
        run: pip install --upgrade setuptools
      - name: Install python deps
        run: pip install -r requirements.txt
      - name: Generate station
        run: PATH=${PWD}/gopath/bin:${PATH} make station; mkdir release; mv station.grf release/
      - name: Pack documentation
        run: cp docs/station/changelog.md release/changelog.txt; cp docs/station/readme.md release/readme.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: china-set-stations-wuhu
          path: release
          retention-days: 7
