name: Unit tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "test"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      # - name: Install golang deps
      #   run: ./install-go-dependencies.sh
      - name: Install system python deps
        run: sudo apt update && sudo apt install python3-ply python3-pil libjpeg-dev zlib1g-dev
      - name: Get setuptools
        run: pip install --upgrade setuptools
      - name: Install python deps
        run: pip install -r requirements.txt && pip install pytest
      - name: Test stations
        run: pytest station
      - name: Test AEGIS
        run: make test.aegis
